### PR TITLE
Some refactors, update gradle wrapper, improve build.gradle

### PR DESCRIPTION
**Pull request by AntoineJT**
- Refactor RecipesManager
- Refactor a bit PredicatesGenerator, CommandHandler, BlockMechanicsListener and ResourcePack
- Remove unused imports
- Update gradle wrapper from 5.2.1 to 5.6.3
- Modify build.gradle in order to add some build infos to MANIFEST.MF

### CODE REVIEW

**Comment by AntoineJT** [comment]
⚠️ DO NOT ACCEPT THIS PR FOR NOW : it seems that Oraxen is now really buggy and has some memory leak

**Comment by Th0rgal** [comment]
Finally fixed hahaha

**Comment by AntoineJT** [comment]
⚠️ DO NOT ACCEPT THIS PR FOR NOW : it seems that Oraxen is not generating pack properly

**Comment by AntoineJT** [comment]
Okay, it seems to be good for now : damn ResourcePack class 😅

**Comment by Th0rgal** [comment]
Yes, I think you understood my suffering.

**Pull request merged**
